version: '3'

services:
  db:
    image: mongo:latest
    volumes:
      - ./mongod.conf:/etc/mongod.conf
    command: 'mongod -f /etc/mongod.conf'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
