version: '3'

services:
  db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./logs:/var/log/mongodb/
    command: 'mongod -f /etc/mongod.conf'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  # bringatrailer:
  #   build: ./miner
  #   links:
  #     - db
  #   volumes:
  #     - ./apps/bringatrailer:/app
  #   working_dir: '/app'
  #   user: $UID
  #   command: 'python3 main.py'

  craigslist:
    build: ./miner
    links:
      - db
    volumes:
      - ./apps/craigslist:/app
    working_dir: '/app'
    user: $UID
    command: 'python3 main.py'

networks:
  default:
  webproxy:
    external:
      name: ${NETWORK:-webproxy}
